
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-mysql
  annotations:
redeploy-timestamp: "2025-12-02T12:12:10Z"
spec:
  template:
    spec:
      containers:
        - name: liquibase-mysql
          image: testacrcacheone.azurecr.io/liquibase-mysql:1.0

