
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquibase-mysql
spec:
  template:
    spec:
      containers:
        - name: liquibase-mysql
          image: testacrcacheone.azurecr.io/liquibase-mysql:1.0

